name: Secret Scan

on:
  push:
    branches:
      - master
      - development
      - task/5-remove-rotate-secrets-6f2rxjc2cxqChQg6
  pull_request:
    branches:
      - master
      - development
      - task/5-remove-rotate-secrets-6f2rxjc2cxqChQg6

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2.9.0
        with:
          args: '--verbose'

      - name: Upload Gitleaks Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
