name: Secret Scan

on:
  push:
    branches:
      - master
      - development
      - task/align-j-unit-platform-dependencies-after-dependabot-upgrade-6fqcFVFFWcQCxPvc
  pull_request:
    branches:
      - master
      - development
      - task/align-j-unit-platform-dependencies-after-dependabot-upgrade-6fqcFVFFWcQCxPvc

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Gitleaks Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
