name: Secret Scan

on:
  push:
    branches:
      - master
      - development
      - task/3-configure-dependabot-sast-code-ql-6f2rxqvrMgCvvM76
  pull_request:
    branches:
      - master
      - development
      - task/3-configure-dependabot-sast-code-ql-6f2rxqvrMgCvvM76

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2.3.9
        with:
          args: '--verbose'

      - name: Upload Gitleaks Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
